In [1]:
import numpy as np
from numpy import random

#### 1. Create a 4x4 Matrix with values ranging from 0 to 3

In [3]:
np.linspace(0,3,16).reshape((4,4))

array([[0. , 0.2, 0.4, 0.6],
       [0.8, 1. , 1.2, 1.4],
       [1.6, 1.8, 2. , 2.2],
       [2.4, 2.6, 2.8, 3. ]])

#### 2. Create an array with shape of 4x4 and turn it into two arrays along the second axis

In [5]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.hsplit(arr, 2)

[array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])]