## Adding, Removing, and Sorting

In [2]:
import numpy as np

In [2]:
# Membuat array dengan tipe data berbeda
# Step 1 : Definisikan tipe
dtype = [('name', 'U10'), ('height', float), ('age', int)]
# Step 2 : Definisikan list
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38)]
# Step 3 : Definisikan array
a = np.array(values, dtype = dtype)
a

array([('Arthur', 1.8, 41), ('Lancelot', 1.9, 38)],
      dtype=[('name', '<U10'), ('height', '<f8'), ('age', '<i4')])

### Append

In [3]:
# Menambahkan array
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.append(arr1, [10,11,12])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
# Ketika axis ditentukan
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Matriks 2D gunakan 2 kurung tutup
np.append(arr2, [[10,11,12]], axis = 0)

# Axis = 0 : Penambahan ke bawah (secara baris)
# Axis = 1 : Ke samping (secara kolom)
# Axis = 2 : Ke dalam
# Menyesuaikan bentuk matriks

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

### Concatenate

In [9]:
# Menggabungkan dua array
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 0)
print(c)

[[ 1  2  8]
 [ 5  8 10]
 [ 8  2  1]
 [ 3  9  1]]


In [10]:
d = np.concatenate((a,b), axis = 1)
d

array([[ 1,  2,  8,  8,  2,  1],
       [ 5,  8, 10,  3,  9,  1]])

In [11]:
# Axis none -> Mendatarkan array
e = np.concatenate((a,b), axis = None)
e

array([ 1,  2,  8,  5,  8, 10,  8,  2,  1,  3,  9,  1])

### Sort

In [12]:
arr3 = np.array([2,3,1,4,7,5,3])
arr3

array([2, 3, 1, 4, 7, 5, 3])

In [13]:
# Ascending sort
np.sort(arr3)

array([1, 2, 3, 3, 4, 5, 7])

In [14]:
# Descending sort
np.sort(arr3)[::-1]

array([7, 5, 4, 3, 3, 2, 1])

### delete

In [17]:
arr4 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,8,10,10]
])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  8, 10, 10]])

In [19]:
# Menghapus satu baris di urutan ke-2
np.delete(arr4, 1, axis = 0)

array([[ 1,  2,  3,  4],
       [ 8,  8, 10, 10]])

In [20]:
# Menghapus satu kolom di urutan ke-1
np.delete(arr4, 0, axis = 1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [ 8, 10, 10]])

## Shape and Size of Array

In [22]:
arr5 = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]]) 
arr5

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

### shape

In [23]:
arr5.shape

(3, 2, 4)

### Size

In [24]:
arr5.size

24

### ndim

In [26]:
# Menghitung dimensi array
arr5.ndim

3

## Reshaping Array

In [27]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Argumen (shape) -> Sesuai jumlah elemen
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
# Belum ditampung hasilnya
a.shape

(10,)

In [33]:
a_reshape = a.reshape((5,2))
# Setelah ditampung hasilnya
a_reshape.shape

(5, 2)

## Excercise 3

1. Create 3x3 Matrix with values from 2 to 10

In [37]:
arr6 = np.linspace(2,10,9)
arr6

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
arr6.reshape((3,3))

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

2. Concatenate the following arrays [[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]


In [40]:
np.concatenate(([[0, 1, 3], [5, 7, 9]], 
                [[0, 2, 4], [6, 8, 10]]), axis = 1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

## Converting 1D to 2D (add new axis)

### newaxis

In [41]:
arr7 = np.arange(6)
arr7

array([0, 1, 2, 3, 4, 5])

In [42]:
arr7.shape

(6,)

In [43]:
arr7.ndim

1

In [48]:
# Menaikkan dimensi array
# Menambahkan satu dimensi di baris
arr7_2d = arr7[np.newaxis, :]
arr7_2d

array([[0, 1, 2, 3, 4, 5]])

In [49]:
arr7_2d.ndim

2

In [50]:
arr7_2d.shape

(1, 6)

In [54]:
# Menambahkan satu dimensi di kolom
arr7_2d = arr7[:, np.newaxis]
arr7_2d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [55]:
arr7_2d.ndim

2

In [56]:
arr7_2d.shape

(6, 1)

### expand_dims

In [57]:
arr8 = np.arange(6)
arr8

array([0, 1, 2, 3, 4, 5])

In [60]:
# Menambah dimensi di kolom
arr8_exdim = np.expand_dims(arr8, axis = 1)
arr8_exdim

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Indexing and Slicing

In [3]:
from numpy import random

In [66]:
arr9 = random.randint(1, 10, size = (2,10))
arr9

array([[2, 6, 9, 8, 1, 9, 2, 7, 6, 8],
       [5, 1, 8, 3, 5, 3, 1, 2, 9, 8]])

In [68]:
# Mengambil nilai di baris ke-1 kolom ke-1
arr9[0,0]

2

In [69]:
# Mengambil nilai semua baris di kolom ke-2
arr9[:, 1]

array([6, 1])

In [70]:
# Mengambil data baris kedua, kolom ke-2 hingga 4
arr9[1, 2:5]

array([8, 3, 5])

In [71]:
# Index bisa negatif, maka urutannya dari belakang
# Titik dua di depan : Mengambil semua angka awal 
#                      sebelum angka batas
arr9[1, :-3]

array([5, 1, 8, 3, 5, 3, 1])

In [72]:
# Titik dua di belakang : Mengambil semua angka akhir 
#                         setelah angka batas
arr9[1, -3:]

array([2, 9, 8])

### Conditional Indexing

In [73]:
# Mengambil array dengan anggota kurang dari 5
arr9[arr9<5]

array([2, 1, 2, 1, 3, 3, 1, 2])

In [76]:
five_up = arr9 >= 5
# Jika tidak diindex, keluaran akan boolean
five_up

array([[False,  True,  True,  True, False,  True, False,  True,  True,
         True],
       [ True, False,  True, False,  True, False, False, False,  True,
         True]])

In [77]:
# Jika diindex maka keluaran akan anggota array
arr9[five_up]

array([6, 9, 8, 9, 7, 6, 8, 5, 8, 5, 9, 8])

In [78]:
divisible_2 = arr9[arr9%2 == 0]
divisible_2

array([2, 6, 8, 2, 6, 8, 8, 2, 8])

#### Conditional Operator

In [80]:
# & : and
arr10 = arr9[(arr9 > 2) & (arr9 < 8)]
arr10

array([6, 7, 6, 5, 3, 5, 3])

In [81]:
# | : or
arr11 = arr9[(arr9<2) | (arr9>8)]
arr11

array([9, 1, 9, 1, 1, 9])

### 3D Array Indexing

In [85]:
arr12 = random.randint(1, 10, size=(2,2,3))
arr12

array([[[7, 9, 5],
        [7, 4, 7]],

       [[4, 4, 6],
        [2, 4, 2]]])

In [86]:
# Access Row
arr12[0]

array([[7, 9, 5],
       [7, 4, 7]])

In [90]:
# Access Row and Column
arr12[0,1]

array([7, 4, 7])

In [91]:
# Access Row, Column, Depth
arr12[0,1,2]

7

## Creating Array from Existing Data

In [92]:
arr13 = np.array([1,2,3,4,5,6,7,8,9,10])
arr13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
a1 = np.array([
    [1,1],
    [2,3]
])

a2 = np.array([
    [2,3],
    [4,4]
])

### vstack

In [94]:
# Menggabungkan secara vertikal
np.vstack((a1,a2))

array([[1, 1],
       [2, 3],
       [2, 3],
       [4, 4]])

### hstack

In [95]:
# Menggabungkan secara horizontal
np.hstack((a1,a2))

array([[1, 1, 2, 3],
       [2, 3, 4, 4]])

### hsplit

In [96]:
# Memisahkan array secara horizontal
a3 = np.arange(1,25).reshape(2,12)
a3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [97]:
# Membagi menjadi 3 array
a4 = np.hsplit(a3, 3)
a4

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [98]:
a4[2]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [100]:
# Membagi menurut angka
# argumen (array, (urutan split))
# Mesplit setelah kolom 3 dan kolom 5
a5 = np.hsplit(a3, (3,5))
a5

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

## Basic Array Operations

In [102]:
a6 = np.array([1,2])
a7 = np.ones(2, dtype=int)

In [103]:
# Penjumlahan
a6 + a7

array([2, 3])

In [104]:
# Pengurangan
a6 - a7

array([0, 1])

In [105]:
# Perkalian
a6*a7

array([1, 2])

In [106]:
# Pembagian
a6/a7

array([1., 2.])

### Sum

In [108]:
# Menjumlahkan semua nilai array
a8 = np.array([1,2,3,4])
a8.sum()

10

In [109]:
a9 = np.array([
    [1,2],
    [3,4]
])
a9

array([[1, 2],
       [3, 4]])

In [112]:
# Memasukkan argumen axis
a9.sum(axis = 0)

array([4, 6])

In [113]:
a9.sum(axis = 1)

array([3, 7])

### Broadcasting

In [5]:
# Mengalikan array dengan skalar
data = np.array([1.0, 2.0])
data*1.6

array([1.6, 3.2])

In [22]:
data1 = np.array([[2, 3, 4]])
data2 = np.array([3, 2, 1])
data2 = data2[:, np.newaxis]
data1.shape

(1, 3)

In [23]:
data2.shape

(3, 1)

In [20]:
# Perkalian array dengan bentuk berbeda
data1*data2

array([[ 6,  9, 12],
       [ 4,  6,  8],
       [ 2,  3,  4]])

In [19]:
# Ketika perkalian dibalik
data2*data1

array([[ 6,  9, 12],
       [ 4,  6,  8],
       [ 2,  3,  4]])

NumPy mengerti bahwa perkalian seharusnya terjadi pada tiap sel. Konsep ini disebut "braodcasting". Braodcasting adalah mekanisme yang membuat NumPy dapat mengoperasikan array dengan bentuk berbeda

## Mathemathical Formula

### Mean Square Error

In [24]:
n = 3
y_pred = np.array([1,1,1])
labels = np.array([1,2,3])
mse = (1/n)*np.sum(np.square(y_pred-labels))
mse

1.6666666666666665

## Save and Load Numpy Objects

In [115]:
a10 = np.array([1,2,3,4,5])
a10

array([1, 2, 3, 4, 5])

### save

In [116]:
# Menyimpan array ke file
# nama file 'array1' dengan ekstensi .npy
np.save('array1', a10)

### load

In [118]:
a11 = np.load('array1.npy')
a11

array([1, 2, 3, 4, 5])

### Format : csv

In [123]:
# Gunakan savetxt untuk menyimpan file
# Tambahkan ekstensi .csv pada penamaan file
np.savetxt('array2.csv', a10)

In [124]:
# Gunakan loadtxt untuk membuka file
a12 = np.loadtxt('array2.csv')
a12

array([1., 2., 3., 4., 5.])

## Excercise 4

1. Create a null vector/ 1D array of size 10 and update  ffith value to 11

In [26]:
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
null[4] = 11
null

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

2. Write a Numpy Program to create a 2x3 arrays and change it into 3x2 arrays

In [28]:
data3 = np.array([
    [2,3,4], 
    [3,2,4]
])
data3

array([[2, 3, 4],
       [3, 2, 4]])

In [29]:
data3.reshape((3,2))

array([[2, 3],
       [4, 3],
       [2, 4]])

3. Write a NumPy program to create a 2D array with 1 on the border and 0 inside

In [32]:
mat = np.ones((5,5))
mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
for i in [1,2,3]:
    for j in [1,2,3]:
        mat[i,j] = 0
mat

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

4. Take a look at the following matrix. Access the [2,1,1]

In [34]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [36]:
z[2,0,:]

array([1, 1, 2])