# Numpy - Multidimensional Data Arrays

## Import Numpy

In [3]:
import numpy as np

In [4]:
## Mengecek versi Numpy
np.__version__

'1.19.2'

In [5]:
## Menampilkan perintah Numpy
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

## Array vs List

In [6]:
# Python List
a = [1,2,3,4]
b = [5,6,7,8]

In [8]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

List tidak mendukung operasi aritmatika. Solusi? Numpy Array

In [9]:
a_array = np.array(a)
b_array = np.array(b)

In [11]:
print(a_array+b_array)
print(a_array*b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## Creating Numpy Array

#### Cara 1: List

In [12]:
# vector - 1D
v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In [13]:
# Matrix - 2D or more - combination of lists
m = np. array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# Check data type
type(v)
type(m)

numpy.ndarray

In [15]:
type(a)

list

Mengecek ukuran array  - shape

In [16]:
v.shape

(4,)

In [17]:
m.shape

(2, 4)

Menghitung jumlah elemen - size

In [18]:
v.size

4

In [19]:
m.size

8

Untuk mengecek tipe data - dtype

In [20]:
m.dtype

dtype('int32')

In [21]:
v.dtype

dtype('int32')

In [23]:
# Untuk mendefinisikan tipe data
v = np.array([1,2,3,4], dtype = float)
v

array([1., 2., 3., 4.])

In [24]:
m = np.array([
    [1,2,3,4],
    [4,5,6,7]
], dtype = complex)
m

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j]])

## Create Matrix Zeros

In [25]:
# One Dimension
z1 = np.zeros(5)
z1

array([0., 0., 0., 0., 0.])

In [26]:
# Two Dimension
z2 = np.zeros(5,4)
z2

TypeError: Cannot interpret '4' as a data type

In [27]:
# Harus berupa Tuple
z2 = np.zeros((5,2))
z2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Creating Matrix Ones

In [29]:
# One Dimension
o1 = np.ones(5)
o1

array([1., 1., 1., 1., 1.])

In [30]:
# Three Dimension
o3 = np.ones((5,4,3))
o3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## Excercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [33]:
np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2. Create the matrix

In [34]:
np.array([
    [2,7,12,0],
    [3,9,3,4],
    [4,0,1,4]
])

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  4]])

3. Create a 2D matrix with a size of 10

In [35]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [36]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

5. Make the following array from zeros arrays and for loops

In [38]:
arr0 = np.zeros((5,3))
for i in [1,2]:
    arr0 = arr0 + np.ones((5,3))
arr0

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

## Using Array-Generating Function

### Arange

In [4]:
# Create a range
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Mirip dengan
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [6]:
# With (start, stop)
x1 = np.arange(10,20)
x1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
# With (start, stop, step)
x2 = np.arange(10,21,2)
x2

array([10, 12, 14, 16, 18, 20])

In [8]:
# Negative argument
x3 = np.arange(-1,1,0.1)
x3

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

### Linspace

In [9]:
# Semua titik ujung dimasukkan
np.linspace(10)

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

In [10]:
# Perlu dua argumen (start, stop)
# Membuat angka dari 1 hingga 10 inklusif
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
x4 = np.linspace(0,10)
x4

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
# Default size = 50
x4.size

50

In [11]:
# Dengan argumen (start, stop, jumlah)
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

### Random

In [12]:
# Import package random
from numpy import random

In [13]:
# Uniform random numbers in [0,1]
# shape -> (5,5)
random.rand(5,5)

array([[0.35858296, 0.40653175, 0.88140842, 0.96938813, 0.4520289 ],
       [0.25674842, 0.25510596, 0.34555753, 0.30996812, 0.78902637],
       [0.50655612, 0.58468749, 0.85548813, 0.42860721, 0.13849789],
       [0.2100063 , 0.13002823, 0.85708447, 0.54993191, 0.49969125],
       [0.64094907, 0.86304687, 0.02350023, 0.32091741, 0.96870104]])

In [14]:
# Standard normal distribution random numbers
# Shape -> (5,5)
random.randn(5,5)

array([[ 0.07135635,  0.80165576,  2.27880522,  3.2138666 , -0.095586  ],
       [ 1.32339111,  0.79195506,  1.45940703,  0.60994683,  1.38422594],
       [-0.87558518, -2.06463259, -0.64055158, -0.5813108 , -0.13926473],
       [-1.37367253, -0.08036185, -0.33453384, -1.44117834,  2.01919158],
       [ 0.81138582, -0.34689722,  0.19418908,  1.39326021, -0.64973696]])

In [16]:
# Random integer value
# argumen (stop)
# Memilih angka random dari 0 sampai 10
random.randint(10)

9

In [17]:
# argumen (start, stop, size)
# Memilih angka random dari 2 ke 10 dengan ukuran 4
random.randint(2,10,4)

array([8, 9, 4, 2])

In [18]:
# argumen (start, stop, size = (shape))
random.randint(2,10, size = (4,3,4))

array([[[4, 7, 7, 2],
        [5, 3, 7, 4],
        [7, 8, 4, 3]],

       [[2, 2, 8, 2],
        [2, 3, 7, 8],
        [7, 2, 8, 5]],

       [[9, 4, 9, 2],
        [6, 9, 3, 7],
        [2, 7, 7, 7]],

       [[4, 3, 5, 2],
        [7, 5, 8, 4],
        [2, 9, 7, 5]]])

## Excercise 2

1. Generate 1-D array containing 5 random integers form 0 to 100

In [19]:
random.randint(0,100,5)

array([17, 49, 14,  7,  6])

2. Generate 2D array with 3 rows, each rows contains 5 random integers from 0 to 100

In [20]:
random.randint(0,100, size = (3,5))

array([[34, 57, 83, 28, 74],
       [50, 21, 43, 31, 92],
       [65, 33, 89, 89, 85]])

3. Generate a 1D array of 30 evenly spaced elements between 1.5 and 5.5 inclusive

In [21]:
np.linspace(1.5,5.5,30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])